#! /bin/bash

usage(){
    echo "Usage: $0 <command> [arguments]"
    echo "Commands:"
    echo "  build     - Build the project"
    echo "  run       - Build and run the project"
    echo "  test      - Run tests"
}

build() {
    clang -Wall -Wextra -Iheaders -o ./out/main ./src/log.c ./src/main.c
}

run() {
    clang -Wall -Wextra -Iheaders -o ./src/log.c ./src/main.c && ./out/main 
}

run1() {
    clang -DDEBUG=1 -Wall -Wextra -Iheaders -o ./out/main ./src/log.c ./src/main.c && ./out/main ./artifacts/sample0.kysql
}

case "$1" in 
    "run")
        run
        ;;

    "run1")
        run1
        ;;

    "build")
        build
        ;;

    "test")
        test
        ;;

    *)
        usage
        ;;
esac